# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KucasinoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KucasinoApp

  pod 'NVActivityIndicatorView'
  pod 'SwiftDate'
  pod 'Alamofire', '~> 5.2.2'
  pod 'AlamofireImage', '~> 4.1.0'
  pod 'AKNumericFormatter'
  pod 'Toast-Swift', '~> 4.0.1'
  pod 'FontAwesome.swift'
  pod 'SkyFloatingLabelTextField'
  pod 'SnapKit'
  pod 'EasyTipView'
  pod 'ActionSheetPicker-3.0'
  pod 'IQKeyboardManagerSwift'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'Cosmos'
  pod 'MBProgressHUD'
  pod 'FirebaseCore', '~> 6.5.0'
  pod 'FirebaseMessaging', '~> 4.1.10'
  pod 'FirebaseAuth', '~> 6.4.1'
  pod 'Codextended'
  pod 'DropDown'
  pod 'Charts'
  pod 'CRRefresh'
  pod 'FSPagerView'
  pod 'SVPinView'
  pod 'RealmSwift', '~> 4.3.2'
  pod 'SideMenu'
  pod 'DKImagePickerController'
  pod 'ActionSheetPicker-3.0'
  pod 'SwiftPullToRefresh'
  pod 'CRRefresh'
  pod 'SKPhotoBrowser'
pod 'RxSwift'
pod 'RxCocoa'
pod 'Kingfisher', '~> 5.12.0'
pod 'SwiftyJSON'
pod 'Eureka'
pod 'Cosmos'
pod 'SVProgressHUD'
pod 'DZNEmptyDataSet'
pod 'RangeSeekSlider'
pod "KWVerificationCodeView", '0.3.0'
pod 'ReadMoreTextView'
pod 'SkeletonView'
pod "ViewAnimator"
pod 'PhotoSlider'
pod 'SwiftGen', '~> 6.0'
pod 'SwiftSoup'

end
